services:
  - type: web
    name: iswitch
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: SUPABASE_URL
        value: https://biqdckcyteswvwcrzuvc.supabase.co
      - key: SUPABASE_PUBLISHABLE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpcWRja2N5dGVzd3Z3Y3J6dXZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcwNzYzODMsImV4cCI6MjA5MjY1MjM4M30.nb1xRdVHMecYPEhLYPia76tzoWpmf0qBxfgDxOdZ_qg
      - key: VITE_SUPABASE_PROJECT_ID
        value: biqdckcyteswvwcrzuvc
      - key: VITE_SUPABASE_URL
        value: https://biqdckcyteswvwcrzuvc.supabase.co
      - key: VITE_SUPABASE_PUBLISHABLE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpcWRja2N5dGVzd3Z3Y3J6dXZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcwNzYzODMsImV4cCI6MjA5MjY1MjM4M30.nb1xRdVHMecYPEhLYPia76tzoWpmf0qBxfgDxOdZ_qg
