services:
  - type: web
    name: viraly-api
    env: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://postgres.ffpcnnxoyklepylgywnt:Forgetpassword2024.@aws-1-eu-west-1.pooler.supabase.com:6543/postgres
      - key: SUPABASE_URL
        value: https://ffpcnnxoyklepylgywnt.supabase.co
      - key: SUPABASE_ANON_KEY
        value: sb_publishable_86lbbyxWOSKZhbxnP9r1cw_wuAUYEq7
      - key: IP_SALT
        value: viraly_secret_salt_2026_nigeria
